### ISSUE TITLE
error using GUI to predict rt

### ISSUE THREAD

**Issue by sehooni** [compomics/DeepLC#53]
Hi

I want to use deeplc to predict retention times for some peptides so I just use deeplc from GUI.
However, there are some problem like below.

2023-05-28 22:43:39 - INFO - Using DeepLC version 2.0.4
Traceback (most recent call last):
  File "deeplc\gui.py", line 38, in <module>
    start_gui()
  File "gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "deeplc\gui.py", line 35, in start_gui
    main(gui=True)
  File "deeplc\__main__.py", line 70, in main
    run(**vars(argu))
  File "deeplc\__main__.py", line 130, in run
    list_of_psms.append(PSM(peptidoform=peprec_to_proforma(seq,mod),spectrum_id=ident))
  File "psm_utils\io\peptide_record.py", line 398, in peprec_to_proforma
    peptide[int(position)] += f"[{label}]"
IndexError: list index out of range
2023-05-28 22:44:05 - INFO - Using DeepLC version 2.0.4
Traceback (most recent call last):
  File "deeplc\gui.py", line 38, in <module>
    start_gui()
  File "gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "deeplc\gui.py", line 35, in start_gui
    main(gui=True)
  File "deeplc\__main__.py", line 70, in main
    run(**vars(argu))
  File "deeplc\__main__.py", line 134, in run
    psm_list_pred = read_file(file_pred)
  File "psm_utils\io\__init__.py", line 125, in read_file
    filetype = _infer_filetype(filename)
  File "psm_utils\io\__init__.py", line 86, in _infer_filetype
    raise PSMUtilsIOException("Could not infer filetype.")
psm_utils.io.exceptions.PSMUtilsIOException: Could not infer filetype.
2023-05-28 22:48:35 - INFO - Using DeepLC version 2.0.4
Traceback (most recent call last):
  File "deeplc\gui.py", line 38, in <module>
    start_gui()
  File "gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "deeplc\gui.py", line 35, in start_gui
    main(gui=True)
  File "deeplc\__main__.py", line 70, in main
    run(**vars(argu))
  File "deeplc\__main__.py", line 134, in run
    psm_list_pred = read_file(file_pred)
  File "psm_utils\io\__init__.py", line 125, in read_file
    filetype = _infer_filetype(filename)
  File "psm_utils\io\__init__.py", line 86, in _infer_filetype
    raise PSMUtilsIOException("Could not infer filetype.")
psm_utils.io.exceptions.PSMUtilsIOException: Could not infer filetype.
2023-05-28 22:49:11 - INFO - Using DeepLC version 2.0.4
Traceback (most recent call last):
  File "deeplc\gui.py", line 38, in <module>
    start_gui()
  File "gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "deeplc\gui.py", line 35, in start_gui
    main(gui=True)
  File "deeplc\__main__.py", line 70, in main
    run(**vars(argu))
  File "deeplc\__main__.py", line 134, in run
    psm_list_pred = read_file(file_pred)
  File "psm_utils\io\__init__.py", line 125, in read_file
    filetype = _infer_filetype(filename)
  File "psm_utils\io\__init__.py", line 86, in _infer_filetype
    raise PSMUtilsIOException("Could not infer filetype.")
psm_utils.io.exceptions.PSMUtilsIOException: Could not infer filetype.
2023-05-28 23:19:30 - INFO - Using DeepLC version 2.0.4
Traceback (most recent call last):
  File "deeplc\gui.py", line 38, in <module>
    start_gui()
  File "gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "deeplc\gui.py", line 35, in start_gui
    main(gui=True)
  File "deeplc\__main__.py", line 70, in main
    run(**vars(argu))
  File "deeplc\__main__.py", line 134, in run
    psm_list_pred = read_file(file_pred)
  File "psm_utils\io\__init__.py", line 125, in read_file
    filetype = _infer_filetype(filename)
  File "psm_utils\io\__init__.py", line 86, in _infer_filetype
    raise PSMUtilsIOException("Could not infer filetype.")
psm_utils.io.exceptions.PSMUtilsIOException: Could not infer filetype.

And my CSV file are like below.
sequence_information.csv
seq,modifications
KPVGAAK,
KPAVQK,
KPLQGK,
VPKQAK,
QVAPKK,
GQLPKK,
AAGVPKK,
PVVLDK,
VPVIDK,
QPKIGK,
KPAAAAGAK,
KPQVNAK,
KPSPEVK,
KPMLPAK,
EPVIAQK,
APLMPKK,
PLDLGAAK,
PKPPAFK,
LPLDQAK,
PKQGINK,
SIHHAR,
SLHAHR,
ISEPFK,
LSIMEK,
LSMIEK,
SLEIMK,
SLEPFK,
SLLEMK,
SLMLEK,
ISFPEK,
KPMLPAK,3|Oxidation
LVWPSAK,
QSVELPK,
GVIEPSAK,
PSLTGLGR,
LGDLGLGR,
AEVVGAVR,
WVLVQR,
APPPPPPK,
DTLINPK,
GQQIGK,
QAGGIGK,
QGQIGK,
QNALGK,
GIVWR,
GLVGER,
GVIDAR,
LGVEGR,
LVGWR,
VGLWR,
QMIQQYEMYCK,10|Carbamidomethyl
TEEMPNDSVLENK,4|Oxidation
KPATAAGTK,
AIHLNK,
....

How can I use deeplc to predict retention time?

**Comment by RobbinBouwmeester** [comment]
Dear sehooni,

I think I have identified the problem. To be sure, could you also share the input file?

Will make a release fixing this issue ASAP.

Kind regards,

Robbin

**Comment by sehooni** [comment]
Thank you for reply,

File size is too big to upload. so I'll send you by email.

Could you inform your email address??

**Comment by RobbinBouwmeester** [comment]
The latest release v2.1.9 should fix your issue, please feel free to re-open this issue if it did not.
