### ISSUE TITLE
GUI DeepLC errors

### ISSUE THREAD

**Issue by MassambaNdiaye** [compomics/DeepLC#71]
Here is the error i get while trying to run DeepLC
2024-03-28 17:20:01 - INFO - Using DeepLC version 2.2.27
Traceback (most recent call last):
  File "deeplc\gui.py", line 38, in <module>
  File "gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
  File "deeplc\gui.py", line 35, in start_gui
  File "deeplc\__main__.py", line 70, in main
  File "deeplc\__main__.py", line 134, in run
  File "psm_utils\io\__init__.py", line 151, in read_file
  File "psm_utils\io\__init__.py", line 112, in _infer_filetype
psm_utils.io.exceptions.PSMUtilsIOException: Could not infer filetype.

**Comment by RobbinBouwmeester** [comment]
Dear MassambaNdiaye,

What file are you trying to run through DeepLC? This error relates to an extension of the file that is not recognized by psm_utils.

So best would be if you check out psm_utils and choose a filetype and extension that DeepLC can work with: [https://github.com/compomics/psm_utils](https://github.com/compomics/psm_utils)

Hope that helps.

**Comment by MassambaNdiaye** [comment]
Dear RobbinBouwmeester,
Thank you a lot. I checked my submitted file and find out that the error was not due to file type but to decimal separator type used in my calibration file. 
Thank you for your help

**Comment by RobbinBouwmeester** [comment]
Ah great that you resolved it! I will have a look to see if I can throw a better error that is more useful for the user.
