### ISSUE TITLE
Cannot add modifications

### ISSUE THREAD

**Issue by grimace9527** [compomics/DeepLC#83]
Hi,

I am trying to add a modification into unimod_to_formula.csv, and I follows the instructions on your main page:

```
Q: I have a modification that is not in unimod. How can I add the modification?

In the folder unimod/ there is the file unimod_to_formula.csv that can be used to add modifications. In the CSV file add a name (that is unique and not present yet) and the change in atomic composition. For example:

Met->Hse,O,H(-2) C(-1) S(-1)
```

However, the modification still cannot be added and the an error was raised when running:

  File "D:\python_projects\python_3_11\Lib\site-packages\pyteomics\proforma.py", line 674, in _resolve_impl
    raise KeyError(name)
KeyError: 'Succinimide D'

and the line I input is :
Succinimide D,,H(-2) O(-1)

I wonder if there is anything wrong with my operation. Thanks for your reply!

Best wishes,
Jim

**Comment by grimace9527** [comment]
And an another question:
when I choose the "Use transfer learning calibration" in the second panel, the software goes wrong like:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\python_projects\python_3_11\Scripts\deeplc-gui.exe\__main__.py", line 7, in <module>
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\deeplc\gui.py", line 35, in start_gui
    main(gui=True)
  File "D:\python_projects\python_3_11\Lib\site-packages\deeplc\__main__.py", line 67, in main
    run(**vars(argu))
  File "D:\python_projects\python_3_11\Lib\site-packages\deeplc\__main__.py", line 183, in run
    dlc.calibrate_preds(psm_list=psm_list_cal)
  File "D:\python_projects\python_3_11\Lib\site-packages\deeplc\deeplc.py", line 1180, in calibrate_preds
    models = deeplcretrainer.retrain(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\deeplcretrainer\deeplcretrainer.py", line 278, in retrain
    df = cnn_functions.get_feat_df(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\deeplcretrainer\cnn_functions.py", line 392, in get_feat_df
    pepper = deeplc.DeepLC(
             ^^^^^^^^^^^^^^
TypeError: deeplc.deeplc.DeepLC() got multiple values for keyword argument 'verbose'

Thanks again for your response!! : )

**Comment by RobbinBouwmeester** [comment]
Hi Jim,

Actually the documentation is a bit out of date for modifications. We now use [psm_utils](https://github.com/compomics/psm_utils) that in turn supports [ProForma](https://github.com/HUPO-PSI/ProForma). Easiest is probably to choose the composition notation.

I will have a look ASAP at the GUI.

Also feel free to contact me directly here: robbin.bouwmeester@ugent.be

I can probably help you with running DeepLC directly.

**Comment by grimace9527** [comment]
Hi Robbin,
Thanks a lot for your response. The ProForma works well.
By the way, I noticed that ProForma supports arbitrary mass shifts:
```
Arbitrary mass shifts and unknown mass gaps
EM[+15.9949]EVEES[-79.9663]PEK
RTAAX[+367.0537]WT
```

But in your article, the element formula and other features of modifications are used in model prediction. I wonder how you deal with this kind of situation (since the element formula may not match to a modification in Unimod). It will help me a lot when it can be explained to me. Thanks!

**Comment by RobbinBouwmeester** [comment]
Yes, proforma supports mass shifts, but unfortunately DeepLC does not. It will likely throw an error (or at least ignore it).

**Comment by grimace9527** [comment]
Thanks, and sorry that I have too many questions...
The default models are full_hc_PXD005573_pub_1fd8363d9af9dcad3be7553c39396960.keras, full_hc_PXD005573_pub_8c22d89667368f2f02ad996469ba157e.keras and full_hc_PXD005573_pub_cb975cfdd4105f97efa0b3afffe075cc.keras. Are they the best models you have trained? I noticed that you provide some models in .hdf5 format on https://github.com/RobbinBouwmeester/DeepLCModels, should I convert these models into .keras format if I want to use them?

Thanks again

**Comment by RobbinBouwmeester** [comment]
Hey,

No worries about the questions, happy to help!

Actually a blog post was written on this recently by Matrix Science: https://www.matrixscience.com/blog/tutorial-selecting-the-best-deeplc-model.html

In terms of the keras vs hdf. I made the switch to .keras from version 3.1 >, because the latest versions of tensorflow do not support .hdf in their old form anymore. I have not updated all models. So if you want to try different models as suggested by the blog, it would be best to run DeepLC < 3.1.0.

Hope that helps :)

**Comment by RobbinBouwmeester** [comment]
They are indeed slightly different, these days we only use a single model for prediction by default. Which in the current case is:

"mods/full_hc_PXD005573_pub_1fd8363d9af9dcad3be7553c39396960.keras"

About the version. I was wrong... I introduced that breaking change since 3.0.0, everything < v2.2.36 should work... Sorry for the confusion.

**Comment by grimace9527** [comment]
Ok I think I get it. I really appreciate your response.
However, when I am trying v2.2.30 DeepLC GUI, and an error raises:
(The command line I use is  python -m deeplc.gui, and it works well with the latest version.)
Could you please take a look?

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\python_projects\python_3_11\Lib\site-packages\deeplc\gui.py", line 38, in <module>
    start_gui()
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 128, in inner2
    return payload(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\deeplc\gui.py", line 35, in start_gui
    main(gui=True)
  File "D:\python_projects\python_3_11\Lib\site-packages\deeplc\__main__.py", line 52, in main
    argu = parse_arguments(gui=gui)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\deeplc\_argument_parser.py", line 266, in parse_arguments
    results = parser.parse_args()
              ^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\python_bindings\gooey_parser.py", line 125, in parse_args
    return self.parser.parse_args(args, namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 123, in run_gooey
    application.run(build_spec)
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\gui\application.py", line 21, in run
    app, _ = build_app(build_spec)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\gui\application.py", line 27, in build_app
    return _build_app(build_spec, app)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\gui\application.py", line 40, in _build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\gui\containers\application.py", line 44, in __init__
    self.configs = self.buildConfigPanels(self)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\gui\containers\application.py", line 242, in buildConfigPanels
    return [page_class(parent, widgets, self.buildSpec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\gui\containers\application.py", line 242, in <listcomp>
    return [page_class(parent, widgets, self.buildSpec)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\gui\components\config.py", line 18, in __init__
    self.layoutComponent()
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\gui\components\config.py", line 211, in layoutComponent
    self.makeGroup(panel, sizer, group, 0, wx.EXPAND)
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\gui\components\config.py", line 141, in makeGroup
    widget = self.reifyWidget(parent, item)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\gui\components\config.py", line 193, in reifyWidget
    return widgetClass(parent, item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\gui\components\widgets\bases.py", line 73, in __init__
    self.widget = self.getWidget(self)
                  ^^^^^^^^^^^^^^^^^^^^
  File "D:\python_projects\python_3_11\Lib\site-packages\gooey\gui\components\widgets\numeric_fields.py", line 13, in getWidget
    widget = self.widget_class(self,
             ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SpinCtrl(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 'min' has unexpected type 'float'
```

**Comment by RobbinBouwmeester** [comment]
Hey, I looked into this and getting the GUI to work for older versions seems to be kinda hard. I will try to fix the latest version and provide all new model files.

**Comment by grimace9527** [comment]
Thanks! I appreciate it and look forward to the new versions : )

**Comment by grimace9527** [comment]
Hi Robbin,
I think I've found some bugs and hope these can helps, and I am looking forward to the new versions. DeepLC really helps me a lot.
In "cnn_functions.py", line 392:
`    pepper = deeplc.DeepLC(
        f_extractor=f_extractor,
        cnn_model=True,
        n_jobs=num_cores,
        verbose=True,
        **kwargs,
    )`

It looks like the "verbose" param should be located before the n_jobs param since these params all have default values when the function is announced.

And in "files.py", line 235:
`        fid = h5f.open(name, flags, fapl=fapl)`
It seems the transfer learning still needs the .hdf5 format models rather than .keras now.

Hope these messages helps.
Thanks for your response and answer again.
: )

**Comment by RobbinBouwmeester** [comment]
OK, I went through all the issues you mentioned here today, and I think everything is resolved :)
